### ISSUE TITLE
Can you prepare some pre-train weight to reproduce the results?

### ISSUE THREAD

**Issue by moonstarsky37** [VictorAlteirac/PFE_Tree_segmentation-using_PointNet2#1]
Hi, the results is pretty good.
Will you prepare some pre-train weight for reproduce the results in https://github.com/VictorAlteirac/PFE_Tree_segmentation-using_PointNet2#visuals-results
Thanks the sharing again.

**Comment by VictorAlteirac** [comment]
No this is not planned, I used PointNet ++ to start learning the basics of NN. I don't intend to continue working on it as new and more performing networks are available. 
I add in the log directory the training logs and the weight file of the trained model.

**Comment by moonstarsky37** [comment]
Thanks for your reply!
